### ISSUE TITLE
arm64 build

### ISSUE THREAD

**Issue by fabiomaia** [feicong/strong-frida#3]
Hey, thanks for sharing this repository! 😄 

I'm still exploring but would like to use the Docker image, however I need to build for arm64 (v8a) not armhf. Could you point me in the right direction?

I think basically I should create a `Dockerfile.arm64` based off some arm64 Docker image, right?

If you are interested I can contribute it back afterwards.

**Comment by fc777888** [comment]
Dockerfile.arm64 added.

**Comment by feicong** [comment]
Dockerfile.arm64 added.

**Comment by fabiomaia** [comment]
Thanks!
